language: node_js
node_js:
  - "v10.13.0"
cache:
  directories:
    - node_modules
env:
  CI: false
before_script:
  - export NODE_OPTIONS="--max-old-space-size=8192"
script:
  - REACT_APP_GIT_SHA_SHORT="git rev-parse --short HEAD" REACT_APP_GIT_SHA_LONG="git rev-parse HEAD" npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
